### ISSUE TITLE
游戏进入存档后一段时间陷入未响应

### ISSUE THREAD

**Issue by mczph** [vfyjxf/JEI-Utilities#6]
https://pastebin.ubuntu.com/p/bXMdwMQryM/
log，未出现crash-report

投到这里的原因是因为看到了这一段，之后就显示我链接终止了
[15:06:27] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$KeyboardInputEvent$Pre@e090627e:
java.lang.NullPointerException: null
	at com.github.vfyjxf.jeiutilities.jei.bookmark.RecipeBookmarkList$RecipeInfo.isResultEquals(RecipeBookmarkList.java:238) ~[RecipeBookmarkList$RecipeInfo.class:?]
	at com.github.vfyjxf.jeiutilities.jei.bookmark.RecipeBookmarkList.lambda$removeRecipeInfo$0(RecipeBookmarkList.java:55) ~[RecipeBookmarkList.class:?]
	at com.github.vfyjxf.jeiutilities.jei.bookmark.RecipeBookmarkList$$Lambda$9606/0000000000000000.test(Unknown Source) ~[?:?]
	at java.util.ArrayList.removeIf(ArrayList.java:1415) ~[?:1.8.0_262]
	at com.github.vfyjxf.jeiutilities.jei.bookmark.RecipeBookmarkList.removeRecipeInfo(RecipeBookmarkList.java:55) ~[RecipeBookmarkList.class:?]
	at com.github.vfyjxf.jeiutilities.gui.bookmark.BookmarkInputHandler.onBookmarkListAddOrRemove(BookmarkInputHandler.java:106) ~[BookmarkInputHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4849_BookmarkInputHandler_onBookmarkListAddOrRemove_KeyboardInputEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:511) [blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(MinecraftMixin.java:1759) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(MinecraftMixin.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(MinecraftMixin.java:5111) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by vfyjxf** [comment]
未响应之前在做什么呢
（由于现在我正在重写这部分代码，我不太清楚这个bug是否还在）

**Comment by vfyjxf** [comment]
你可以使用一下发布的0.2.6预览版看看是否还有这个问题（注意，现在jei utilities修改了配方的存储位置以及格式，之前存储的数据都被废弃了） @mczph

**Comment by mczph** [comment]
好的我去试试

**Comment by mczph** [comment]
看起来没啥问题了
